### ISSUE TITLE
I expect the i18n placeholder translations to work

### ISSUE THREAD

**Issue by kieranklaassen** [bootstrap-ruby/bootstrap_form#169]
When I add these translations:

``` yaml

---
en:
  helpers:
      placeholders:
        model_name:
          field_name: Placeholder text
```

I expect the corresponding field to be populated with the corresponding placeholder.

It does not work now.
