### ISSUE TITLE
Support "^ validation error text" format

### ISSUE THREAD

**Issue by Zmokizmoghi** [bootstrap-ruby/bootstrap_form#447]
Hi.
Russian is a fairly complex language, and russian rails community adopted a hack to achieve human readable complex validation messages. The thing is to drop attribute name and wrote custom validations text for required attribute with `^` at the beginning, for example:
```
ru:
  activerecord:
    errors:
      models:
        person:
          attributes:
            password:
              too_long: "^Ваш пароль слишком длинный, максимум: %{count} символов"

```
Popular gem for handle russian locale also [supports it](https://github.com/yaroslav/russian/blob/master/lib/russian/active_model_ext/custom_error_message.rb#L57)

But this hack lead to wrong help-text form invalid input:

![image](https://user-images.githubusercontent.com/1971059/37032833-cc15c2a4-217e-11e8-8669-3135f92b7df0.png)

Will you accept pull request with fix?
